# Generated by Django 3.1.1 on 2020-10-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=220)),
                ('desc', models.TextField(blank=True)),
                ('size', models.IntegerField(default=3)),
                ('high_priority', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('closed', models.DateTimeField(blank=True, default=None)),
            ],
        ),
    ]
