# Generated by Django 3.1.1 on 2020-10-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='closed',
        ),
    ]
