# Generated by Django 3.1.1 on 2020-10-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20201029_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(blank=True, help_text='(No es obligatorio)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='size',
            field=models.IntegerField(choices=[(1, 'Trivial'), (2, 'Pequeña'), (3, 'Normal'), (4, 'Grande'), (5, 'Muy Grande')], default=3, help_text='5 posibles tamaños', verbose_name='Tamaño de la tarea'),
        ),
    ]
