# Generated by Django 3.1.1 on 2020-10-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20201029_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.SlugField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('about', models.TextField(blank=True, help_text='(No es obligatorio)', verbose_name='Acerca de...')),
                ('started', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
